apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: whereami-http
  namespace: whereami-http
spec:
  selector:
    matchLabels:
      app: whereami-http
  endpoints:
  - port: http #metrics
    interval: 30s